version: '3.8'
services:
  webnoithat:
    image: XiaoYingLiu/webnoithat:latest
    container_name: webnoithat-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production