services:
  - type: web
    name: webnoithat
    env: docker
    plan: free
    region: singapore
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000